version: "3.9"

services:
  app-db:
    image: postgres:15
    container_name: app-db
    environment:
      POSTGRES_DB: codeme_db
      POSTGRES_USER: codeme
      POSTGRES_PASSWORD: codeme_pw
    volumes:
      - app-db-data:/var/lib/postgresql/data
      - ./DB/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - codeme-net
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./env/.env.backend
    depends_on:
      - app-db
    ports:
      - "9000:9000"
    networks:
      - codeme-net
    volumes:
      - ./backend/app:/app/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 9000
      --reload

  n8n-db:
    image: postgres:15
    container_name: n8n-db
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_pw
    volumes:
      - n8n-db-data:/var/lib/postgresql/data
    networks:
      - codeme-net

  n8n:
    image: n8nio/n8n:1.121.2
    container_name: n8n
    env_file:
      - ./env/.env.n8n
    depends_on:
      - n8n-db
    ports:
      - "5678:5678"
    networks:
      - codeme-net
    volumes:
      - ./n8n_data:/home/node/.n8n

networks:
  codeme-net:

volumes:
  app-db-data:
  n8n-db-data:
